### ISSUE TITLE
Using Workflow

### ISSUE THREAD

**Issue by sidikbilardi** [Edujugon/laradoo#3]
How can we update workflow like Validate Invoice ?

**Comment by Edujugon** [comment]
Hi @sidikbilardi ,

WorkFlow feature is not integrated in this package yet.
It's definitely something that future releases should have but I can't provide an ETA since I'm currently quite busy on different projects..

Anyway, it's always more than welcome any contribution. if that's the case, just create a PR and I'll review it and merge.
